export const ADMIN_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_FAILURE = "ADMIN_PRODUCT_FAILURE";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_ADD = "ADMIN_PRODUCT_ADD";
export const ADMIN_PRODUCT_UPDATE = "ADMIN_PRODUCT_UPDATE";
export const ADMIN_PRODUCT_DELETE = "ADMIN_PRODUCT_DELETE";
export const ADMIN_USERS_SUCCESS= "ADMIN_USERS_SUCCESS";
export const ADMIN_USERS_DELETE= "ADMIN_USERS_DELETE";

